# Generated by Django 5.1 on 2024-09-02 11:04

import django.db.models.deletion
import django.db.models.functions.text
import myapp.helpers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='category name')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_lower_name')],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='task name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='task description')),
                ('status', models.IntegerField(choices=[(1, 'New'), (2, 'In progress'), (3, 'Pending'), (4, 'Blocked'), (5, 'Done')], default=1, verbose_name='task status')),
                ('deadline', models.DateTimeField(default=myapp.helpers.end_of_month, verbose_name='deadline date and time')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation date and time')),
                ('categories', models.ManyToManyField(blank=True, related_name='tasks', related_query_name='tasks', to='myapp.category', verbose_name='task categories')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', related_query_name='task', to=settings.AUTH_USER_MODEL, verbose_name='task owner')),
            ],
            options={
                'verbose_name': 'task',
                'db_table': '"my_app_task"',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='subtask name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='subtask description')),
                ('status', models.IntegerField(choices=[(1, 'New'), (2, 'In progress'), (3, 'Pending'), (4, 'Blocked'), (5, 'Done')], default=1, verbose_name='subtask status')),
                ('deadline', models.DateTimeField(default=myapp.helpers.end_of_month, verbose_name='deadline date and time')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation date and time')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', related_query_name='subtask', to=settings.AUTH_USER_MODEL, verbose_name='subtask owner')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', related_query_name='subtask', to='myapp.task', verbose_name='main task')),
            ],
            options={
                'verbose_name': 'subtask',
                'db_table': '"my_app_subtask"',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('title'), name='myapp_task_name_lower_unique'),
        ),
        migrations.AddConstraint(
            model_name='subtask',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('title'), name='myapp_subtask_name_lower_unique'),
        ),
    ]
